// Code generated by dockyard; DO NOT EDIT.
//
// TypeScript contract types — the UI-facing half of the Design A codegen
// pipeline (RFC §6.2). Generated from the Go contract structs by github.com/
// gzuidhof/tygo. The Go struct is the single source of truth (P1); regenerate
// with `dockyard generate` and never edit this file by hand.

/**
 * RenderOutput is the common result shape for tools that produce a media file.
 * Reused across convert/trim/cinematic so the model (and any future UI) sees a
 * consistent payload.
 */
export interface RenderOutput {
  /**
   * OutputPath is the path to the produced file.
   */
  output_path: string;
  /**
   * JobID is the render job's id (usable to cancel an in-flight job).
   */
  job_id: string;
  /**
   * DurationSec is the output's duration in seconds.
   */
  duration_sec: number /* float64 */;
  /**
   * Width and Height are the output video dimensions (0 for audio-only).
   */
  width: number /* int */;
  height: number /* int */;
  /**
   * SizeBytes is the output file size.
   */
  size_bytes: number /* int64 */;
  /**
   * Command is the FFmpeg command line that produced the file (for transparency
   * and debugging); it is never re-executed from this string.
   */
  command: string;
}
/**
 * ProbeMediaInput selects a media file to inspect.
 */
export interface ProbeMediaInput {
  /**
   * Path is the media file to probe. Required.
   */
  path: string;
}
/**
 * ProbeMediaOutput is the typed result of probing a media file.
 */
export interface ProbeMediaOutput {
  /**
   * Path is the probed file.
   */
  path: string;
  /**
   * FormatName is the container format (e.g. "mov,mp4,m4a,...").
   */
  format_name: string;
  /**
   * DurationSec is the media duration in seconds.
   */
  duration_sec: number /* float64 */;
  /**
   * SizeBytes is the file size.
   */
  size_bytes: number /* int64 */;
  /**
   * BitRate is the overall bit rate in bits per second.
   */
  bit_rate: number /* int64 */;
  /**
   * HasVideo / HasAudio report stream presence.
   */
  has_video: boolean;
  has_audio: boolean;
  /**
   * Width and Height are the primary video stream's dimensions.
   */
  width: number /* int */;
  height: number /* int */;
  /**
   * FPS is the primary video stream's frame rate.
   */
  fps: number /* float64 */;
  /**
   * VideoCodec / AudioCodec are the codec names of the primary streams.
   */
  video_codec: string;
  audio_codec: string;
  /**
   * Streams is the total number of streams in the file.
   */
  streams: number /* int */;
}
/**
 * ConvertVideoInput re-encodes a video to a new container / codec / size.
 */
export interface ConvertVideoInput {
  /**
   * InputPath is the source media. Required.
   */
  input_path: string;
  /**
   * OutputPath is the destination; its extension selects the container
   * (e.g. ".mp4", ".webm", ".gif"). Required.
   */
  output_path: string;
  /**
   * VideoCodec overrides the video codec (e.g. "libx264", "libx265",
   * "libvpx-vp9"). Empty uses a sensible default for the container.
   */
  video_codec?: string;
  /**
   * AudioCodec overrides the audio codec (e.g. "aac", "libopus"). Empty uses
   * a sensible default.
   */
  audio_codec?: string;
  /**
   * CRF is the quality factor (lower = higher quality; ~18–28 for x264).
   * Zero means the codec default.
   */
  crf?: number /* int */;
  /**
   * Preset is the x264/x265 speed/efficiency preset (e.g. "medium", "slow").
   */
  preset?: string;
  /**
   * Scale resizes the output, formatted "WxH" (e.g. "1280x720"). Empty keeps
   * the source size.
   */
  scale?: string;
  /**
   * FPS overrides the output frame rate. Zero keeps the source rate.
   */
  fps?: number /* int */;
}
/**
 * TrimVideoInput cuts a time range out of a video.
 */
export interface TrimVideoInput {
  /**
   * InputPath is the source media. Required.
   */
  input_path: string;
  /**
   * OutputPath is the destination. Required.
   */
  output_path: string;
  /**
   * StartSeconds is the in-point. Defaults to 0.
   */
  start_seconds?: number /* float64 */;
  /**
   * EndSeconds is the out-point. Must be greater than StartSeconds. Required.
   */
  end_seconds: number /* float64 */;
  /**
   * ReEncode forces a frame-accurate re-encode. When false (the default) the
   * trim is a fast stream copy that cuts at the nearest keyframe.
   */
  re_encode?: boolean;
}
/**
 * ExtractAudioInput pulls the audio track out of a media file.
 */
export interface ExtractAudioInput {
  /**
   * InputPath is the source media. Required.
   */
  input_path: string;
  /**
   * OutputPath is the destination; its extension selects the audio format
   * (".mp3", ".m4a", ".wav", ".flac"). Required.
   */
  output_path: string;
  /**
   * Bitrate sets the encoded audio bitrate (e.g. "192k"). Empty uses a
   * sensible default; ignored for lossless formats.
   */
  bitrate?: string;
}
/**
 * ExtractAudioOutput is the result of an audio extraction.
 */
export interface ExtractAudioOutput {
  /**
   * OutputPath is the produced audio file.
   */
  output_path: string;
  /**
   * JobID is the render job's id.
   */
  job_id: string;
  /**
   * DurationSec is the audio duration in seconds.
   */
  duration_sec: number /* float64 */;
  /**
   * SizeBytes is the output file size.
   */
  size_bytes: number /* int64 */;
}
/**
 * TransitionStyle selects how one image gives way to the next.
 * Allowed: "none", "fade", "wipe", "slide", "zoom_blur", "film_dissolve",
 * "random_safe".
 */
export type TransitionStyle = string;
/**
 * MotionStyle selects the per-image camera motion (the "Ken Burns" family).
 * Allowed: "none", "ken_burns", "slow_push", "pan_left", "pan_right",
 * "parallax_like".
 */
export type MotionStyle = string;
/**
 * ColorGrade selects the final cinematic look applied to the whole reel.
 * Allowed: "neutral", "warm", "cinematic", "vintage", "high_contrast".
 */
export type ColorGrade = string;
/**
 * Caption is a timed text overlay (lower-third / title). Accepted by the
 * contract for forward-compatibility; rendering lands in a later layer (V4) and
 * any captions supplied today are reported back in Warnings, not yet burned in.
 */
export interface Caption {
  /**
   * Text is the caption text.
   */
  text: string;
  /**
   * StartSeconds / EndSeconds bound when the caption is shown.
   */
  start_seconds: number /* float64 */;
  end_seconds: number /* float64 */;
  /**
   * Position is a named placement ("lower_third", "center", "top").
   */
  position?: string;
}
/**
 * CreateCinematicImageVideoInput is the input for the flagship tool: it compiles
 * a sequence of images into a cinematic slideshow video — canvas, motion,
 * transitions, colour grade, and an optional music bed — in a single render.
 */
export interface CreateCinematicImageVideoInput {
  /**
   * Images are the ordered source image paths. At least one is required.
   */
  images: string[];
  /**
   * OutputPath is the destination video (".mp4" recommended). Required.
   */
  output_path: string;
  /**
   * Canvas is the output frame size: "1920x1080" (landscape), "1080x1920"
   * (portrait/reel), or a custom "WxH". Defaults to "1920x1080".
   */
  canvas?: string;
  /**
   * FPS is the output frame rate. Defaults to 30.
   */
  fps?: number /* int */;
  /**
   * DurationPerImage is the on-screen seconds per image. Defaults to 4.
   * Ignored when TotalDuration is set.
   */
  duration_per_image?: number /* float64 */;
  /**
   * TotalDuration, when set, fixes the whole reel's length and the per-image
   * duration is derived from it (handy for matching a song length).
   */
  total_duration?: number /* float64 */;
  /**
   * TransitionStyle selects the join between images. Defaults to "fade".
   */
  transition_style?: TransitionStyle;
  /**
   * TransitionSeconds is the crossfade duration. Defaults to 1.
   */
  transition_seconds?: number /* float64 */;
  /**
   * MotionStyle selects per-image camera motion. Defaults to "ken_burns".
   */
  motion_style?: MotionStyle;
  /**
   * ColorGrade selects the final look. Defaults to "neutral".
   */
  color_grade?: ColorGrade;
  /**
   * BackgroundAudio is an optional music bed (audio file path).
   */
  background_audio?: string;
  /**
   * AudioFadeInSeconds / AudioFadeOutSeconds fade the music bed. Default 0.
   */
  audio_fade_in_seconds?: number /* float64 */;
  audio_fade_out_seconds?: number /* float64 */;
  /**
   * Captions are timed text overlays. Accepted now; burned-in rendering is a
   * later layer — supplied captions are echoed in Warnings until then.
   */
  captions?: Caption[];
  /**
   * Watermark is an optional overlay image path. Planned; echoed in Warnings.
   */
  watermark?: string;
  /**
   * BeatSync, when true, would align transitions to the music beat. Planned;
   * echoed in Warnings.
   */
  beat_sync?: boolean;
  /**
   * SafeArea, when true, would keep content inside a title-safe margin.
   * Planned; echoed in Warnings.
   */
  safe_area?: boolean;
}
/**
 * CreateCinematicImageVideoOutput is the flagship tool's result.
 */
export interface CreateCinematicImageVideoOutput {
  /**
   * Render carries the produced file's path, dimensions, duration, and the
   * FFmpeg command used.
   */
  render: RenderOutput;
  /**
   * ImageCount is how many images were composited.
   */
  image_count: number /* int */;
  /**
   * PerImageSeconds is the resolved on-screen seconds per image.
   */
  per_image_seconds: number /* float64 */;
  /**
   * FilterComplex is the compiled FFmpeg filtergraph — the storyboard of the
   * render, surfaced so the model can explain or refine it.
   */
  filter_complex: string;
  /**
   * Warnings lists any supplied options that are accepted by the contract but
   * not yet rendered (e.g. captions, watermark, beat_sync).
   */
  warnings?: string[];
}
