// Code generated by dockyard; DO NOT EDIT.
//
// TypeScript contract types — the UI-facing half of the Design A codegen
// pipeline (RFC §6.2). Generated from the Go contract structs by github.com/
// gzuidhof/tygo. The Go struct is the single source of truth (P1); regenerate
// with `dockyard generate` and never edit this file by hand.

/**
 * RenderOutput is the common result shape for tools that produce a media file.
 * Reused across convert/trim/cinematic so the model (and any future UI) sees a
 * consistent payload.
 */
export interface RenderOutput {
  /**
   * OutputPath is the path to the produced file.
   */
  output_path: string;
  /**
   * JobID is the render job's id (usable to cancel an in-flight job).
   */
  job_id: string;
  /**
   * DurationSec is the output's duration in seconds.
   */
  duration_sec: number /* float64 */;
  /**
   * Width and Height are the output video dimensions (0 for audio-only).
   */
  width: number /* int */;
  height: number /* int */;
  /**
   * SizeBytes is the output file size.
   */
  size_bytes: number /* int64 */;
  /**
   * Command is the FFmpeg command line that produced the file (for transparency
   * and debugging); it is never re-executed from this string.
   */
  command: string;
}
/**
 * ProbeMediaInput selects a media file to inspect.
 */
export interface ProbeMediaInput {
  /**
   * Path is the media file to probe. Required.
   */
  path: string;
}
/**
 * ProbeMediaOutput is the typed result of probing a media file.
 */
export interface ProbeMediaOutput {
  /**
   * Path is the probed file.
   */
  path: string;
  /**
   * FormatName is the container format (e.g. "mov,mp4,m4a,...").
   */
  format_name: string;
  /**
   * DurationSec is the media duration in seconds.
   */
  duration_sec: number /* float64 */;
  /**
   * SizeBytes is the file size.
   */
  size_bytes: number /* int64 */;
  /**
   * BitRate is the overall bit rate in bits per second.
   */
  bit_rate: number /* int64 */;
  /**
   * HasVideo / HasAudio report stream presence.
   */
  has_video: boolean;
  has_audio: boolean;
  /**
   * Width and Height are the primary video stream's dimensions.
   */
  width: number /* int */;
  height: number /* int */;
  /**
   * FPS is the primary video stream's frame rate.
   */
  fps: number /* float64 */;
  /**
   * VideoCodec / AudioCodec are the codec names of the primary streams.
   */
  video_codec: string;
  audio_codec: string;
  /**
   * Streams is the total number of streams in the file.
   */
  streams: number /* int */;
}
/**
 * ConvertVideoInput re-encodes a video to a new container / codec / size.
 */
export interface ConvertVideoInput {
  /**
   * InputPath is the source media. Required.
   */
  input_path: string;
  /**
   * OutputPath is the destination; its extension selects the container
   * (e.g. ".mp4", ".webm", ".gif"). Required.
   */
  output_path: string;
  /**
   * VideoCodec overrides the video codec (e.g. "libx264", "libx265",
   * "libvpx-vp9"). Empty uses a sensible default for the container.
   */
  video_codec?: string;
  /**
   * AudioCodec overrides the audio codec (e.g. "aac", "libopus"). Empty uses
   * a sensible default.
   */
  audio_codec?: string;
  /**
   * CRF is the quality factor (lower = higher quality; ~18–28 for x264).
   * Zero means the codec default.
   */
  crf?: number /* int */;
  /**
   * Preset is the x264/x265 speed/efficiency preset (e.g. "medium", "slow").
   */
  preset?: string;
  /**
   * Scale resizes the output, formatted "WxH" (e.g. "1280x720"). Empty keeps
   * the source size.
   */
  scale?: string;
  /**
   * FPS overrides the output frame rate. Zero keeps the source rate.
   */
  fps?: number /* int */;
}
/**
 * TrimVideoInput cuts a time range out of a video.
 */
export interface TrimVideoInput {
  /**
   * InputPath is the source media. Required.
   */
  input_path: string;
  /**
   * OutputPath is the destination. Required.
   */
  output_path: string;
  /**
   * StartSeconds is the in-point. Defaults to 0.
   */
  start_seconds?: number /* float64 */;
  /**
   * EndSeconds is the out-point. Must be greater than StartSeconds. Required.
   */
  end_seconds: number /* float64 */;
  /**
   * ReEncode forces a frame-accurate re-encode. When false (the default) the
   * trim is a fast stream copy that cuts at the nearest keyframe.
   */
  re_encode?: boolean;
}
/**
 * ExtractAudioInput pulls the audio track out of a media file.
 */
export interface ExtractAudioInput {
  /**
   * InputPath is the source media. Required.
   */
  input_path: string;
  /**
   * OutputPath is the destination; its extension selects the audio format
   * (".mp3", ".m4a", ".wav", ".flac"). Required.
   */
  output_path: string;
  /**
   * Bitrate sets the encoded audio bitrate (e.g. "192k"). Empty uses a
   * sensible default; ignored for lossless formats.
   */
  bitrate?: string;
}
/**
 * ExtractAudioOutput is the result of an audio extraction.
 */
export interface ExtractAudioOutput {
  /**
   * OutputPath is the produced audio file.
   */
  output_path: string;
  /**
   * JobID is the render job's id.
   */
  job_id: string;
  /**
   * DurationSec is the audio duration in seconds.
   */
  duration_sec: number /* float64 */;
  /**
   * SizeBytes is the output file size.
   */
  size_bytes: number /* int64 */;
}
/**
 * MediaItem describes one media file the server can read.
 */
export interface MediaItem {
  /**
   * Path is the absolute, validated path (feed it straight to other tools).
   */
  path: string;
  /**
   * Name is the file's base name.
   */
  name: string;
  /**
   * Kind is the media class: "image", "audio", or "video".
   */
  kind: string;
  /**
   * Ext is the lower-case extension including the dot (e.g. ".jpg").
   */
  ext: string;
  /**
   * SizeBytes is the file size.
   */
  size_bytes: number /* int64 */;
}
/**
 * ListMediaInput browses media files under the server's allowed roots.
 */
export interface ListMediaInput {
  /**
   * Dir optionally restricts the listing to a subdirectory (must resolve
   * inside an allowed root). Empty lists across all allowed roots.
   */
  dir?: string;
  /**
   * Kinds optionally filters by media class ("image", "audio", "video").
   * Empty returns all media kinds.
   */
  kinds?: string[];
}
/**
 * ListMediaOutput is the result of a media listing.
 */
export interface ListMediaOutput {
  /**
   * Items are the media files found (capped; see Truncated).
   */
  items: MediaItem[];
  /**
   * Roots are the allowed roots that were searched.
   */
  roots: string[];
  /**
   * Truncated is true when the listing hit the item cap and more files exist.
   */
  truncated?: boolean;
}
/**
 * IngestMediaInput accepts a file uploaded through the UI (base64 bytes) and
 * persists it under the server's work directory so other tools can read it by
 * path. This is how a host-side drag-and-drop becomes a server-side file.
 */
export interface IngestMediaInput {
  /**
   * Filename is the original file name; only its base name is used.
   */
  filename: string;
  /**
   * DataBase64 is the file's bytes, base64-encoded (std encoding).
   */
  data_base64: string;
}
/**
 * IngestMediaOutput reports where the uploaded file landed.
 */
export interface IngestMediaOutput {
  /**
   * Path is the validated path of the persisted file.
   */
  path: string;
  /**
   * Name is the (possibly de-duplicated) base name written.
   */
  name: string;
  /**
   * Kind is the detected media class.
   */
  kind: string;
  /**
   * SizeBytes is the persisted size.
   */
  size_bytes: number /* int64 */;
}
/**
 * ReadMediaInput reads a media file back as bytes so a sandboxed UI can play or
 * display it (the iframe can't read server paths directly).
 */
export interface ReadMediaInput {
  /**
   * Path is the media file to read (must resolve inside an allowed root).
   */
  path: string;
}
/**
 * ReadMediaOutput carries the file as a data URI, or reports it was too large.
 */
export interface ReadMediaOutput {
  /**
   * DataURI is "data:<mime>;base64,<...>" — directly usable as an <img>/<video>
   * /<audio> src. Empty when Truncated is true.
   */
  data_uri?: string;
  /**
   * Mime is the detected MIME type.
   */
  mime: string;
  /**
   * SizeBytes is the file's size on disk.
   */
  size_bytes: number /* int64 */;
  /**
   * Truncated is true when the file exceeds the inline read cap; DataURI is
   * then empty and the caller should fall back to a path/poster.
   */
  truncated?: boolean;
}
/**
 * TransitionStyle selects how one image gives way to the next.
 * Allowed: "none", "fade", "wipe", "slide", "zoom_blur", "film_dissolve",
 * "random_safe".
 */
export type TransitionStyle = string;
/**
 * MotionStyle selects the per-image camera motion (the "Ken Burns" family).
 * Allowed: "none", "ken_burns" (gentle centred push), "slow_push" (stronger
 * centred push), "pan_left" / "pan_right" (lateral drift, no zoom),
 * "diagonal_drift" (zoom while drifting across both axes), "parallax_like"
 * (a pronounced zoom with a horizontal slide — a parallax feel).
 */
export type MotionStyle = string;
/**
 * ColorGrade selects the final cinematic look applied to the whole reel.
 * Allowed: "neutral", "warm", "cinematic", "vintage", "high_contrast".
 */
export type ColorGrade = string;
/**
 * Template names a cinematic preset — a curated bundle of canvas, motion,
 * transition, colour grade, and timing that yields a polished reel in one shot.
 * The template only fills fields the caller leaves unset; any explicit field
 * (canvas, motion_style, color_grade, …) overrides the template's value.
 * Allowed: "none" (default — apply plain defaults), "wedding_reel" (warm,
 * unhurried Ken Burns with soft dissolves), "product_launch" (punchy 9:16
 * slow-push with quick slides, high contrast), "memory_montage" (nostalgic
 * Ken Burns + vintage grade), "travel_diary" (lateral pans, wipes, cinematic).
 */
export type Template = string;
/**
 * Caption is a timed text overlay (lower-third / title). Accepted by the
 * contract for forward-compatibility; rendering lands in a later layer (V4) and
 * any captions supplied today are reported back in Warnings, not yet burned in.
 */
export interface Caption {
  /**
   * Text is the caption text.
   */
  text: string;
  /**
   * StartSeconds / EndSeconds bound when the caption is shown.
   */
  start_seconds: number /* float64 */;
  end_seconds: number /* float64 */;
  /**
   * Position is a named placement ("lower_third", "center", "top").
   */
  position?: string;
}
/**
 * PerClip carries optional per-image overrides for the flagship tool, indexed
 * to Images (clip i overrides image i). It is sparse: set only the fields you
 * want to customise; an empty/zero field inherits the corresponding global
 * setting. The Clips slice may be shorter than Images — unlisted images use the
 * globals throughout.
 */
export interface PerClip {
  /**
   * Motion overrides MotionStyle for this image. Empty inherits the global.
   */
  motion?: MotionStyle;
  /**
   * Transition overrides the transition style INTO the next image (the join
   * after this clip). Empty inherits the global. Ignored on the last image and
   * when the global transition is "none" (a hard-cut reel — per-join hard cuts
   * inside a blended reel are not yet supported).
   */
  transition?: TransitionStyle;
  /**
   * DurationSeconds overrides this image's on-screen seconds. Zero inherits the
   * resolved global per-image duration.
   */
  duration_seconds?: number /* float64 */;
}
/**
 * CreateCinematicImageVideoInput is the input for the flagship tool: it compiles
 * a sequence of images into a cinematic slideshow video — canvas, motion,
 * transitions, colour grade, and an optional music bed — in a single render.
 */
export interface CreateCinematicImageVideoInput {
  /**
   * Images are the ordered source image paths. At least one is required.
   */
  images: string[];
  /**
   * Template applies a named cinematic preset (canvas/motion/transition/grade/
   * timing). It fills only the fields left unset below — any explicit field
   * overrides the template. Defaults to "none" (plain defaults). See Template.
   */
  template?: Template;
  /**
   * OutputPath is the destination video (".mp4" recommended). Optional: when
   * empty, the server writes a uniquely-named reel into its work directory
   * and returns the path (so a UI need not know server paths).
   */
  output_path?: string;
  /**
   * Canvas is the output frame size: "1920x1080" (landscape), "1080x1920"
   * (portrait/reel), or a custom "WxH". Defaults to "1920x1080".
   */
  canvas?: string;
  /**
   * FPS is the output frame rate. Defaults to 30.
   */
  fps?: number /* int */;
  /**
   * DurationPerImage is the on-screen seconds per image. Defaults to 4.
   * Ignored when TotalDuration is set.
   */
  duration_per_image?: number /* float64 */;
  /**
   * TotalDuration, when set, fixes the whole reel's length and the per-image
   * duration is derived from it (handy for matching a song length).
   */
  total_duration?: number /* float64 */;
  /**
   * TransitionStyle selects the join between images. Defaults to "fade".
   */
  transition_style?: TransitionStyle;
  /**
   * TransitionSeconds is the crossfade duration. Defaults to 1.
   */
  transition_seconds?: number /* float64 */;
  /**
   * MotionStyle selects the default per-image camera motion. Defaults to
   * "ken_burns". Override individual images with Clips.
   */
  motion_style?: MotionStyle;
  /**
   * Clips optionally overrides motion / transition / duration per image,
   * indexed to Images (sparse; may be shorter than Images). The global fields
   * remain the defaults for any image or field left unset.
   */
  clips?: PerClip[];
  /**
   * ColorGrade selects the final look. Defaults to "neutral".
   */
  color_grade?: ColorGrade;
  /**
   * BackgroundAudio is an optional music bed (audio file path).
   */
  background_audio?: string;
  /**
   * AudioFadeInSeconds / AudioFadeOutSeconds fade the music bed. Default 0.
   */
  audio_fade_in_seconds?: number /* float64 */;
  audio_fade_out_seconds?: number /* float64 */;
  /**
   * NormalizeAudio loudness-normalises the music bed via a single-pass
   * loudnorm (EBU R128, ~-16 LUFS) so beds of differing loudness sound even.
   * Defaults to true when omitted; set false to skip. Single-pass (not the
   * two-pass measure-then-apply), which is plenty for a background bed.
   */
  normalize_audio?: boolean;
  /**
   * Captions are timed text overlays. Accepted now; burned-in rendering is a
   * later layer — supplied captions are echoed in Warnings until then.
   */
  captions?: Caption[];
  /**
   * Watermark is an optional overlay image path. Planned; echoed in Warnings.
   */
  watermark?: string;
  /**
   * BeatSync, when true and BPM > 0, snaps each transition (or hard cut) to
   * the music beat by rounding the per-image advance to a whole number of
   * beats. BPM-driven (no onset detection) — supply the track's tempo. When
   * BeatSync is set without a positive BPM it is reported in Warnings.
   */
  beat_sync?: boolean;
  /**
   * BPM is the music tempo (beats per minute) used for BeatSync. Ignored
   * unless BeatSync is true. There is no auto-detection — pass the known BPM.
   */
  bpm?: number /* float64 */;
  /**
   * SafeArea, when true, would keep content inside a title-safe margin.
   * Planned; echoed in Warnings.
   */
  safe_area?: boolean;
}
/**
 * CreateCinematicImageVideoOutput is the flagship tool's result.
 */
export interface CreateCinematicImageVideoOutput {
  /**
   * Render carries the produced file's path, dimensions, duration, and the
   * FFmpeg command used.
   */
  render: RenderOutput;
  /**
   * ImageCount is how many images were composited.
   */
  image_count: number /* int */;
  /**
   * PerImageSeconds is the resolved on-screen seconds per image.
   */
  per_image_seconds: number /* float64 */;
  /**
   * FilterComplex is the compiled FFmpeg filtergraph — the storyboard of the
   * render, surfaced so the model can explain or refine it.
   */
  filter_complex: string;
  /**
   * Warnings lists any supplied options that are accepted by the contract but
   * not yet rendered (e.g. captions, watermark, beat_sync).
   */
  warnings?: string[];
}
