// Package contracts holds this server's tool input and output contracts.
//
// These typed Go structs are the SOURCE OF TRUTH for each tool's schema
// (Dockyard P1 — contract-first). The JSON Schema and TypeScript alongside this
// file are GENERATED by `dockyard generate`; never hand-edit a generated file.
// Change a contract here, then regenerate.
package contracts

// RenderOutput is the common result shape for tools that produce a media file.
// Reused across convert/trim/cinematic so the model (and any future UI) sees a
// consistent payload.
type RenderOutput struct {
	// OutputPath is the path to the produced file.
	OutputPath string `json:"output_path"`
	// JobID is the render job's id (usable to cancel an in-flight job).
	JobID string `json:"job_id"`
	// DurationSec is the output's duration in seconds.
	DurationSec float64 `json:"duration_sec"`
	// Width and Height are the output video dimensions (0 for audio-only).
	Width  int `json:"width"`
	Height int `json:"height"`
	// SizeBytes is the output file size.
	SizeBytes int64 `json:"size_bytes"`
	// Command is the FFmpeg command line that produced the file (for transparency
	// and debugging); it is never re-executed from this string.
	Command string `json:"command"`
}

// --- probe_media -----------------------------------------------------------

// ProbeMediaInput selects a media file to inspect.
type ProbeMediaInput struct {
	// Path is the media file to probe. Required.
	Path string `json:"path"`
}

// ProbeMediaOutput is the typed result of probing a media file.
type ProbeMediaOutput struct {
	// Path is the probed file.
	Path string `json:"path"`
	// FormatName is the container format (e.g. "mov,mp4,m4a,...").
	FormatName string `json:"format_name"`
	// DurationSec is the media duration in seconds.
	DurationSec float64 `json:"duration_sec"`
	// SizeBytes is the file size.
	SizeBytes int64 `json:"size_bytes"`
	// BitRate is the overall bit rate in bits per second.
	BitRate int64 `json:"bit_rate"`
	// HasVideo / HasAudio report stream presence.
	HasVideo bool `json:"has_video"`
	HasAudio bool `json:"has_audio"`
	// Width and Height are the primary video stream's dimensions.
	Width  int `json:"width"`
	Height int `json:"height"`
	// FPS is the primary video stream's frame rate.
	FPS float64 `json:"fps"`
	// VideoCodec / AudioCodec are the codec names of the primary streams.
	VideoCodec string `json:"video_codec"`
	AudioCodec string `json:"audio_codec"`
	// Streams is the total number of streams in the file.
	Streams int `json:"streams"`
}

// --- convert_video ---------------------------------------------------------

// ConvertVideoInput re-encodes a video to a new container / codec / size.
type ConvertVideoInput struct {
	// InputPath is the source media. Required.
	InputPath string `json:"input_path"`
	// OutputPath is the destination; its extension selects the container
	// (e.g. ".mp4", ".webm", ".gif"). Required.
	OutputPath string `json:"output_path"`
	// VideoCodec overrides the video codec (e.g. "libx264", "libx265",
	// "libvpx-vp9"). Empty uses a sensible default for the container.
	VideoCodec string `json:"video_codec,omitempty"`
	// AudioCodec overrides the audio codec (e.g. "aac", "libopus"). Empty uses
	// a sensible default.
	AudioCodec string `json:"audio_codec,omitempty"`
	// CRF is the quality factor (lower = higher quality; ~18–28 for x264).
	// Zero means the codec default.
	CRF int `json:"crf,omitempty"`
	// Preset is the x264/x265 speed/efficiency preset (e.g. "medium", "slow").
	Preset string `json:"preset,omitempty"`
	// Scale resizes the output, formatted "WxH" (e.g. "1280x720"). Empty keeps
	// the source size.
	Scale string `json:"scale,omitempty"`
	// FPS overrides the output frame rate. Zero keeps the source rate.
	FPS int `json:"fps,omitempty"`
}

// --- trim_video ------------------------------------------------------------

// TrimVideoInput cuts a time range out of a video.
type TrimVideoInput struct {
	// InputPath is the source media. Required.
	InputPath string `json:"input_path"`
	// OutputPath is the destination. Required.
	OutputPath string `json:"output_path"`
	// StartSeconds is the in-point. Defaults to 0.
	StartSeconds float64 `json:"start_seconds,omitempty"`
	// EndSeconds is the out-point. Must be greater than StartSeconds. Required.
	EndSeconds float64 `json:"end_seconds"`
	// ReEncode forces a frame-accurate re-encode. When false (the default) the
	// trim is a fast stream copy that cuts at the nearest keyframe.
	ReEncode bool `json:"re_encode,omitempty"`
}

// --- extract_audio ---------------------------------------------------------

// ExtractAudioInput pulls the audio track out of a media file.
type ExtractAudioInput struct {
	// InputPath is the source media. Required.
	InputPath string `json:"input_path"`
	// OutputPath is the destination; its extension selects the audio format
	// (".mp3", ".m4a", ".wav", ".flac"). Required.
	OutputPath string `json:"output_path"`
	// Bitrate sets the encoded audio bitrate (e.g. "192k"). Empty uses a
	// sensible default; ignored for lossless formats.
	Bitrate string `json:"bitrate,omitempty"`
}

// ExtractAudioOutput is the result of an audio extraction.
type ExtractAudioOutput struct {
	// OutputPath is the produced audio file.
	OutputPath string `json:"output_path"`
	// JobID is the render job's id.
	JobID string `json:"job_id"`
	// DurationSec is the audio duration in seconds.
	DurationSec float64 `json:"duration_sec"`
	// SizeBytes is the output file size.
	SizeBytes int64 `json:"size_bytes"`
}

// --- list_media / ingest_media (Frameline Studio media intake) -------------

// MediaItem describes one media file the server can read.
type MediaItem struct {
	// Path is the absolute, validated path (feed it straight to other tools).
	Path string `json:"path"`
	// Name is the file's base name.
	Name string `json:"name"`
	// Kind is the media class: "image", "audio", or "video".
	Kind string `json:"kind"`
	// Ext is the lower-case extension including the dot (e.g. ".jpg").
	Ext string `json:"ext"`
	// SizeBytes is the file size.
	SizeBytes int64 `json:"size_bytes"`
}

// ListMediaInput browses media files under the server's allowed roots.
type ListMediaInput struct {
	// Dir optionally restricts the listing to a subdirectory (must resolve
	// inside an allowed root). Empty lists across all allowed roots.
	Dir string `json:"dir,omitempty"`
	// Kinds optionally filters by media class ("image", "audio", "video").
	// Empty returns all media kinds.
	Kinds []string `json:"kinds,omitempty"`
}

// ListMediaOutput is the result of a media listing.
type ListMediaOutput struct {
	// Items are the media files found (capped; see Truncated).
	Items []MediaItem `json:"items"`
	// Roots are the allowed roots that were searched.
	Roots []string `json:"roots"`
	// Truncated is true when the listing hit the item cap and more files exist.
	Truncated bool `json:"truncated,omitempty"`
}

// IngestMediaInput accepts a file uploaded through the UI (base64 bytes) and
// persists it under the server's work directory so other tools can read it by
// path. This is how a host-side drag-and-drop becomes a server-side file.
type IngestMediaInput struct {
	// Filename is the original file name; only its base name is used.
	Filename string `json:"filename"`
	// DataBase64 is the file's bytes, base64-encoded (std encoding).
	DataBase64 string `json:"data_base64"`
}

// IngestMediaOutput reports where the uploaded file landed.
type IngestMediaOutput struct {
	// Path is the validated path of the persisted file.
	Path string `json:"path"`
	// Name is the (possibly de-duplicated) base name written.
	Name string `json:"name"`
	// Kind is the detected media class.
	Kind string `json:"kind"`
	// SizeBytes is the persisted size.
	SizeBytes int64 `json:"size_bytes"`
}

// --- read_media (in-iframe playback) ---------------------------------------

// ReadMediaInput reads a media file back as bytes so a sandboxed UI can play or
// display it (the iframe can't read server paths directly).
type ReadMediaInput struct {
	// Path is the media file to read (must resolve inside an allowed root).
	Path string `json:"path"`
}

// ReadMediaOutput carries the file as a data URI, or reports it was too large.
type ReadMediaOutput struct {
	// DataURI is "data:<mime>;base64,<...>" — directly usable as an <img>/<video>
	// /<audio> src. Empty when Truncated is true.
	DataURI string `json:"data_uri,omitempty"`
	// Mime is the detected MIME type.
	Mime string `json:"mime"`
	// SizeBytes is the file's size on disk.
	SizeBytes int64 `json:"size_bytes"`
	// Truncated is true when the file exceeds the inline read cap; DataURI is
	// then empty and the caller should fall back to a path/poster.
	Truncated bool `json:"truncated,omitempty"`
}

// --- open_studio / open_media_uploader (App entry points) ------------------

// OpenStudioInput opens the Frameline Studio composer card — the interactive
// surface for arranging stills and rendering a cinematic reel. Every field is
// optional: call it with no args to open an empty composer the user can drop
// stills into, or pre-fill it.
type OpenStudioInput struct {
	// Images optionally pre-loads the composer with these image paths (each must
	// resolve inside an allowed root). Empty opens an empty composer.
	Images []string `json:"images,omitempty"`
	// Template optionally pre-selects a cinematic template (see Template).
	Template Template `json:"template,omitempty"`
}

// OpenStudioOutput drives the composer view of the Frameline App. Kind is the
// App's view discriminator.
type OpenStudioOutput struct {
	// Kind selects the App view. Always "studio".
	Kind string `json:"kind"`
	// Message is a short human-facing note shown with the card.
	Message string `json:"message"`
	// Images echoes any pre-load paths the App should seed the filmstrip with.
	Images []string `json:"images,omitempty"`
	// Template echoes any pre-selected template.
	Template Template `json:"template,omitempty"`
}

// OpenMediaUploaderInput opens the Media Uploader card — a dedicated drop-zone
// for getting photos and music onto the server (via ingest_media) before
// composing a reel. It takes no required fields; the user drops files into the
// card and the App ingests them.
type OpenMediaUploaderInput struct {
	// Note optionally shows a short prompt at the top of the uploader (e.g.
	// "Drop the wedding photos here"). Optional.
	Note string `json:"note,omitempty"`
}

// OpenMediaUploaderOutput drives the uploader view of the Frameline App.
type OpenMediaUploaderOutput struct {
	// Kind selects the App view. Always "media_uploader".
	Kind string `json:"kind"`
	// Note echoes the optional prompt.
	Note string `json:"note,omitempty"`
	// Roots are the server's allowed media roots, so the card can show where
	// uploaded files land.
	Roots []string `json:"roots"`
}

// --- create_cinematic_image_video ------------------------------------------

// TransitionStyle selects how one image gives way to the next.
// Allowed: "none", "fade", "wipe", "slide", "zoom_blur", "film_dissolve",
// "random_safe".
type TransitionStyle string

// MotionStyle selects the per-image camera motion (the "Ken Burns" family).
// Allowed: "none", "ken_burns" (gentle centred push), "slow_push" (stronger
// centred push), "pan_left" / "pan_right" (lateral drift, no zoom),
// "diagonal_drift" (zoom while drifting across both axes), "parallax_like"
// (a pronounced zoom with a horizontal slide — a parallax feel).
type MotionStyle string

// ColorGrade selects the final cinematic look applied to the whole reel.
// Allowed: "neutral", "warm", "cinematic", "vintage", "high_contrast".
type ColorGrade string

// Template names a cinematic preset — a curated bundle of canvas, motion,
// transition, colour grade, and timing that yields a polished reel in one shot.
// The template only fills fields the caller leaves unset; any explicit field
// (canvas, motion_style, color_grade, …) overrides the template's value.
// Allowed: "none" (default — apply plain defaults), "wedding_reel" (warm,
// unhurried Ken Burns with soft dissolves), "product_launch" (punchy 9:16
// slow-push with quick slides, high contrast), "memory_montage" (nostalgic
// Ken Burns + vintage grade), "travel_diary" (lateral pans, wipes, cinematic).
type Template string

// Caption is a timed text overlay (lower-third / title). Accepted by the
// contract for forward-compatibility; rendering lands in a later layer (V4) and
// any captions supplied today are reported back in Warnings, not yet burned in.
type Caption struct {
	// Text is the caption text.
	Text string `json:"text"`
	// StartSeconds / EndSeconds bound when the caption is shown.
	StartSeconds float64 `json:"start_seconds"`
	EndSeconds   float64 `json:"end_seconds"`
	// Position is a named placement ("lower_third", "center", "top").
	Position string `json:"position,omitempty"`
}

// PerClip carries optional per-image overrides for the flagship tool, indexed
// to Images (clip i overrides image i). It is sparse: set only the fields you
// want to customise; an empty/zero field inherits the corresponding global
// setting. The Clips slice may be shorter than Images — unlisted images use the
// globals throughout.
type PerClip struct {
	// Motion overrides MotionStyle for this image. Empty inherits the global.
	Motion MotionStyle `json:"motion,omitempty"`
	// Transition overrides the transition style INTO the next image (the join
	// after this clip). Empty inherits the global. Ignored on the last image and
	// when the global transition is "none" (a hard-cut reel — per-join hard cuts
	// inside a blended reel are not yet supported).
	Transition TransitionStyle `json:"transition,omitempty"`
	// DurationSeconds overrides this image's on-screen seconds. Zero inherits the
	// resolved global per-image duration.
	DurationSeconds float64 `json:"duration_seconds,omitempty"`
}

// CreateCinematicImageVideoInput is the input for the flagship tool: it compiles
// a sequence of images into a cinematic slideshow video — canvas, motion,
// transitions, colour grade, and an optional music bed — in a single render.
type CreateCinematicImageVideoInput struct {
	// Images are the ordered source image paths. At least one is required.
	Images []string `json:"images"`
	// Template applies a named cinematic preset (canvas/motion/transition/grade/
	// timing). It fills only the fields left unset below — any explicit field
	// overrides the template. Defaults to "none" (plain defaults). See Template.
	Template Template `json:"template,omitempty"`
	// OutputPath is the destination video (".mp4" recommended). Optional: when
	// empty, the server writes a uniquely-named reel into its work directory
	// and returns the path (so a UI need not know server paths).
	OutputPath string `json:"output_path,omitempty"`
	// Canvas is the output frame size: "1920x1080" (landscape), "1080x1920"
	// (portrait/reel), or a custom "WxH". Defaults to "1920x1080".
	Canvas string `json:"canvas,omitempty"`
	// FPS is the output frame rate. Defaults to 30.
	FPS int `json:"fps,omitempty"`
	// DurationPerImage is the on-screen seconds per image. Defaults to 4.
	// Ignored when TotalDuration is set.
	DurationPerImage float64 `json:"duration_per_image,omitempty"`
	// TotalDuration, when set, fixes the whole reel's length and the per-image
	// duration is derived from it (handy for matching a song length).
	TotalDuration float64 `json:"total_duration,omitempty"`
	// TransitionStyle selects the join between images. Defaults to "fade".
	TransitionStyle TransitionStyle `json:"transition_style,omitempty"`
	// TransitionSeconds is the crossfade duration. Defaults to 1.
	TransitionSeconds float64 `json:"transition_seconds,omitempty"`
	// MotionStyle selects the default per-image camera motion. Defaults to
	// "ken_burns". Override individual images with Clips.
	MotionStyle MotionStyle `json:"motion_style,omitempty"`
	// Clips optionally overrides motion / transition / duration per image,
	// indexed to Images (sparse; may be shorter than Images). The global fields
	// remain the defaults for any image or field left unset.
	Clips []PerClip `json:"clips,omitempty"`
	// ColorGrade selects the final look. Defaults to "neutral".
	ColorGrade ColorGrade `json:"color_grade,omitempty"`
	// BackgroundAudio is an optional music bed (audio file path).
	BackgroundAudio string `json:"background_audio,omitempty"`
	// AudioFadeInSeconds / AudioFadeOutSeconds fade the music bed. Default 0.
	AudioFadeInSeconds  float64 `json:"audio_fade_in_seconds,omitempty"`
	AudioFadeOutSeconds float64 `json:"audio_fade_out_seconds,omitempty"`
	// NormalizeAudio loudness-normalises the music bed via a single-pass
	// loudnorm (EBU R128, ~-16 LUFS) so beds of differing loudness sound even.
	// Defaults to true when omitted; set false to skip. Single-pass (not the
	// two-pass measure-then-apply), which is plenty for a background bed.
	NormalizeAudio *bool `json:"normalize_audio,omitempty"`
	// Captions are timed text overlays. Accepted now; burned-in rendering is a
	// later layer — supplied captions are echoed in Warnings until then.
	Captions []Caption `json:"captions,omitempty"`
	// Watermark is an optional overlay image path. Planned; echoed in Warnings.
	Watermark string `json:"watermark,omitempty"`
	// BeatSync, when true and BPM > 0, snaps each transition (or hard cut) to
	// the music beat by rounding the per-image advance to a whole number of
	// beats. BPM-driven (no onset detection) — supply the track's tempo. When
	// BeatSync is set without a positive BPM it is reported in Warnings.
	BeatSync bool `json:"beat_sync,omitempty"`
	// BPM is the music tempo (beats per minute) used for BeatSync. Ignored
	// unless BeatSync is true. There is no auto-detection — pass the known BPM.
	BPM float64 `json:"bpm,omitempty"`
	// SafeArea, when true, would keep content inside a title-safe margin.
	// Planned; echoed in Warnings.
	SafeArea bool `json:"safe_area,omitempty"`
}

// CreateCinematicImageVideoOutput is the flagship tool's result.
type CreateCinematicImageVideoOutput struct {
	// Render carries the produced file's path, dimensions, duration, and the
	// FFmpeg command used.
	Render RenderOutput `json:"render"`
	// ImageCount is how many images were composited.
	ImageCount int `json:"image_count"`
	// PerImageSeconds is the resolved on-screen seconds per image.
	PerImageSeconds float64 `json:"per_image_seconds"`
	// FilterComplex is the compiled FFmpeg filtergraph — the storyboard of the
	// render, surfaced so the model can explain or refine it.
	FilterComplex string `json:"filter_complex"`
	// Warnings lists any supplied options that are accepted by the contract but
	// not yet rendered (e.g. captions, watermark, beat_sync).
	Warnings []string `json:"warnings,omitempty"`
}
